zuul:
  routes:
    service-calculator:
      url: http://service-calculator:5555
    service-database:
      url: http://service-database:6666


ribbon:
  eureka:
    enabled: false


logging:
  level:
    org.springframework.web: DEBUG
    pl.agh.servicecalculator: DEBUG

spring:
  application:
    name: api-gateway
  mvc:
    log-request-details: true