zuul:
  ignoredServices: '*'
  routes:
    service-calculator:
      path: /service-calculator/**
      serviceId: service-calculator
    service-database:
      path: /service-database/**
      serviceId: service-database
    service-history:
      path: /service-history/**
      serviceId: service-history

server:
  contextPath: /
  port: 8080

logging:
  level:
    org.springframework.web: DEBUG
    pl.agh.servicecalculator: DEBUG

spring:
  application:
    name: api-gateway
    velocity.enabled: false
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        hostName: api-gateway
        instanceId: ${spring.application.name}:${random.value}
        healthCheckInterval: 60s
  mvc:
    log-request-details: true

info.component: api-gateway

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false