server:
  port: 5555

logging:
  level:
    org.springframework.web: DEBUG
    pl.agh.servicecalculator: DEBUG

spring:
  application:
    name: service-calculator
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        healthCheckInterval: 60s
  mvc:
    log-request-details: true