server:
  port: 5555

logging:
  level:
    org.springframework.web: DEBUG
    pl.agh.servicecalculator: DEBUG

spring:
  application:
    name: service-calculator
  mvc:
    log-request-details: true